include $(PIQI_ROOT)/make/Makefile.ocaml
include $(PIQI_ROOT)/piqilib/Makefile.piqi_common


PIQIC_LIB_SOURCES = \
	piqic_common.ml \
	piqic_ocaml_types.ml \
	piqic_ocaml_out.ml \
	piqic_ocaml_in.ml \
	piqic_ocaml_defaults.ml \
	piqic_ocaml_base.ml \


SOURCES += $(PIQIC_LIB_SOURCES)

PRE_TARGETS += $(PIQI_SOURCES) $(PIQIC_LIB_SOURCES)


all: dc top #bc


$(PIQIC_LIB_SOURCES): %.ml: $(PIQI_ROOT)/piqic/%.ml
	ln -s $< $@

