#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


RUN="test run"
ERL_PATH=$PIQI_ROOT/piqi-erlang/ebin


erl -pa $ERL_PATH -noshell -s piqi_tools start -run $RUN "$1" -s erlang halt

