%% Copyright 2009, 2010, 2011 Anton Lavrik
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%

%%
%% @doc Runtime support library for Piqi extended
%%
%% This module is used by modules generated by "piqic-erlang-ext" command-line
%% tool.
%%
-module(piqirun_ext).
-compile(export_all).

-include("piqirun.hrl").

-include("piqi_tools_piqi.hrl").


-type input_format() :: piqi_tools_format().

-type output_format() :: input_format() | 'json_pretty' | 'xml_pretty'.


-spec convert/5 :: (
    PiqiMod :: atom(), % Erlang module generated by "piqic-erlang-ext"
    TypeName :: string() | binary(),
    InputFormat :: input_format(),
    OutputFormat :: output_format(),
    Data :: binary() ) -> Data :: binary().

convert(_PiqiMod, _TypeName, X, X, Data) -> Data;

convert(PiqiMod, TypeName, InputFormat, OutputFormat0, Data) ->
    {OutputFormat, PrettyPrint} =
        case OutputFormat0 of
            'json_pretty' -> {'json', true};
            'xml_pretty' -> {'xml', true};
            OF -> {OF, false}
        end,
    case piqi_tools:convert(PiqiMod, TypeName, InputFormat, OutputFormat, Data, PrettyPrint) of
        {ok, X} -> X;
        {error, Error} ->
            throw({'piqirun_ext_error', Error})
    end.

