#!/bin/sh

if [ $# -ne 1 ]
then
    echo "Usage: $0 ADDRESS_BOOK_FILE"
    exit 1
fi


RUN="list_people run"
ERL_PATH=$PIQI_ROOT/piqirun-erlang/ebin


erl -pa $ERL_PATH -noshell -run $RUN "$1" -s erlang halt

