#!/bin/sh

set -ex

# create a binary representation of the addressbook by converting it from piq
piqi convert -t pb addressbook.piq

# create another copy of addressbook records using ocaml program
./add_person_ocaml addressbook.pb <<!
0
J. Random Hacker
j.r.hacker@example.com
(111) 123 45 67
home
(222) 123 45 67
mobile
(333) 123 45 67
work
(444) 123 45 67
mobile

!

./add_person_ocaml addressbook.pb <<!
1
Joe User


!

./add_person_ocaml addressbook.pb <<!
2
Joe User Jr


!

./add_person_ocaml addressbook.pb <<!
3
Joe User II
joe.user@example.com
(444) 123 45 67
home
(555) 123 45 67
work

!


./list_people_ocaml addressbook.piq.pb > l1
./list_people_ocaml addressbook.pb > l2
cmp l1 l2


piqi convert --piqtype addressbook/address-book addressbook.pb > addressbook.pb.piq

rm addressbook.pb

