OCAMLMAKEFILE := $(PIQI_ROOT)/make/OCamlMakefile


OCAMLFIND_DESTDIR = $(PIQI_BUILD)/lib/ocaml
OCAMLPATH = $(OCAMLFIND_DESTDIR)
export OCAMLFIND_DESTDIR OCAMLPATH


.PHONY: piqi-all pre_target post_target


piqi-all: pre_target all post_target

pre_target::

post_target::


# vim:ft=make
