(*
   Copyright 2009, 2010, 2011, 2012 Anton Lavrik

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*)

(*
 * Piq AST (abstract syntax tree)
 *)


module rec Piq_ast :
             sig
type ast =
 [
   | `int of int64
   | `uint of int64
   | `float of float
   | `bool of bool
   | `word of string
   | `ascii_string of string
   | `utf8_string of string
   | `binary of string
   | `text of string
   | `name of string
   | `named of Named.t (* TODO: string * ast *)
   | `typename of string
   | `typed of Typed.t (* TODO: string * ast *)
   | `list of ast list
   | `control of ast list

   (* These two token types are used only in several special cases, and can't be
    * represented in Piq text format directly *)

   (* Raw word -- a valid utf8 Piq word: may be parsed as either of these: word,
    * bool, number, string, binary *)
   | `raw_word of string

   (* Raw binary -- just a sequence of bytes: may be parsed as either binary or
    * utf8 string *)
   | `raw_binary of string

   (* reference to Piqobj.any object in Piqi_objstore *)
   | `any of int
 ]

    end = Piq_ast
and
  Typed :
    sig
      type t =
        { mutable typename : string; mutable value : Piq_ast.ast
        }
      
    end = Typed

and
  Named :
    sig
      type t =
        { mutable name : string; mutable value : Piq_ast.ast
        }
      
    end = Named


include Piq_ast


(* these functions are not going to be used; this are just stubs for
 * autogenerated Piqi-OCaml type mapping *)
let ast_of_bool x = `bool x
let ast_to_bool _ = true

